server:
  port: 8084

spring:
  application:
    name: indian-bank-withdraw-service

  datasource:
    url: jdbc:mysql://localhost:3306/withdraw__service_dev
    username: root
    password: Rishikumar12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

